---
- hosts: all
  remote_user: qaadm
  become: yes
  become_user: root
  tasks:

   - name: Verificando se o processo do {{ app_name }} está no ar
     shell: ps aux | grep -v grep | grep './{{ item }}' | awk '{print $2}' | wc -l
     register: process_to_kill
     with_items: "{{ app_name.split('|') }}"
