---
    - name: Recuperando o caminho do {{ app_name_checksum }} no servidor de destino
      find:
        paths: /home/qaadm/
        file_type: file
        patterns: "^{{ app_name_checksum }}.*tar.gz"
        use_regex: true
        get_checksum: yes
      register: dest_filepath

#    - debug: var=dest_filepath

    - name: Checksum dos arquivos
      debug:
        msg: "O destino não possui ou está com uma versão atualizada do binário"
      when: "{{ item.checksum != local_file_checksum }}"
      with_items: "{{ dest_filepath.files | default([]) }}"
