---
- hosts: all
  remote_user: qaadm
  become: yes
  become_user: root
  gather_facts: no
  tasks:
    - name: Insert a line at the end of a file
      lineinfile:
        path: /etc/hosts
        line: '10.129.176.66 elk2'
#        state: absent
