---
    - name: Validando o diretório destino
      file:
        path: /opt/elk/applications/bin
        state: directory
        follow: yes
        owner: elastic
        group: web
        recurse: no

    - name: Validando o arquivo {{ app_name_extracao }}.tar.gz no destino
      copy:
        src: "{{ cp_item }}"
        dest: "/opt/elk/applications/bin/{{ app_name_extracao }}.tar.gz"
        owner: elastic
        group: web
        force: yes
        follow: true
      with_fileglob: /etc/ansible/stage/replicacaoELK/bin/{{ app_name_extracao }}*tar.gz
      register: copied_files
      loop_control:
        loop_var: cp_item

    - name: Executando a tarefa de export para o binário do {{ app_name_extracao }}
      include: extraction-suite.yml app_name_export={{ app_name_extracao }}
      when: export_item.changed
      with_items: "{{ copied_files.results }}"
      loop_control:
        loop_var: export_item
