---
- name: Validando o arquivo de configuração no servidor de destino (Shippers)
  include: update-shippers.yml app_name_update={{ item }}
  with_items: "{{ app_name.split('|') }}"
  #loop: "{{ app_name.split('|') | flatten(levels=1) }}" #Disponível a partir da versão 2.5 do Ansible
  when: technology == "shipper"

- name: Validando o arquivo de configuração no servidor de destino (ELK)
  include: update-suite.yml app_name_update={{ item }}
  with_items: "{{ app_name.split('|') }}"
  #loop: "{{ app_name.split('|') | flatten(levels=1) }}" #Disponível a partir da versão 2.5 do Ansible
  when: technology == "suite"
