---
- name: Verificando se o processo do {{ app_name_restart }} está no ar
  shell: ps aux | grep -v grep | grep './{{ app_name_restart }}' | awk '{print $2}' | wc -l
  register: process_to_kill
  changed_when: process_to_kill != "0"

- name: Parando o processo
  shell: kill $(ps aux | grep -v grep | grep './{{ app_name_restart }}' | awk '{print $2}')
  when: process_to_kill.stdout != "0"

- name: Iniciando o processo
  shell: nohup ./{{ app_name_restart }} -e -c config/{{ app_name_restart }}.yml > /dev/null 2>&1 &
  args:
    chdir: "{{ install_path.shippers }}/{{ app_name_restart }}/"
