---
- name: Copiando o arquivo de configuração do {{ app_name_update }} para máquina de destino
  copy:
    src: config/{{ app_name_update }}/config/
    dest: "{{ install_path.suite }}/{{ app_name_update }}/config/"
    owner: elastic
    group: web
    mode: 0644
    follow: yes
  register: updated

- name: Reiniciando o processo do {{ app_name_update }}
  include: restart-suite.yml app_name_restart={{ app_name_update }}
  when: updated.changed
