---
- name: Verificando se o processo do {{ app_name_health }} está no ar
  shell: ps aux | grep -v grep | grep '/{{ app_name_health }}' | awk '{print $2}' | wc -l
  register: is_process_alive
  changed_when: is_process_alive.stdout == "0"

- name: Iniciando o processo do Logstash
  become: yes
  become_user: elastic
  shell: "nohup {{ install_path.suite }}/{{ app_name_health }}/bin/{{ app_name_health }} > /dev/null 2>&1 &"
  environment:
    JAVA_HOME: /opt/web/java/
  when: (app_name_health == "logstash" and is_process_alive.stdout == "0")

- name: Iniciando o processo do Kibana
  become: yes
  become_user: elastic
  raw: "nohup {{ install_path.suite }}/{{ app_name_health }}/bin/{{ app_name_health }} > /dev/null 2>&1 &"
  when: (app_name_health == "kibana" and is_process_alive.stdout == "0")

