---
- name: Verificando o status do processo no servidor de destino (Shippers)
  include: health-shippers.yml app_name_health={{ item | regex_replace('-.*', '') }}
  with_items: "{{ app_name.split('|') }}"
  #loop: "{{ app_name.split('|') | flatten(levels=1) }}" #Disponível a partir da versão 2.5 do Ansible
  when: technology == "shipper"

- name: Verificando o status do processo no servidor de destino (ELK)
  include: health-suite.yml app_name_health={{ item }}
  with_items: "{{ app_name.split('|') }}"
  #loop: "{{ app_name.split('|') | flatten(levels=1) }}" #Disponível a partir da versão 2.5 do Ansible
  when: technology == "suite"
