---
- name: Validando o diretório destino
  file:
    path: "{{ install_path.suite }}/bin"
    state: directory
    follow: yes
    owner: elastic
    group: web
    recurse: no

- name: Validando o arquivo {{ app_name_extracao }}.tar.gz no destino
  copy:
    src: "{{ cp_item }}"
    dest: "{{ install_path.suite }}/bin/{{ app_name_extracao }}.tar.gz"
    owner: elastic
    group: web
    force: yes
    follow: yes
  with_fileglob: bin/{{ app_name_extracao }}*tar.gz
  #loop: "{{ lookup('fileglob', 'bin/{{ app_name_extracao }}*tar.gz', wantlist=True) }}" #Disponível a partir da versão 2.5 do Ansible
  register: copied_files
  loop_control:
    loop_var: cp_item

- name: Executando a tarefa de export para o binário do {{ app_name_extracao }}
  include: extraction-suite.yml
  when: export_item.changed
  with_items: "{{ copied_files.results }}"
  #loop: "{{ copied_files.results | flatten(levels=1) }}" #Disponível a partir da versão 2.5 do Ansible
  loop_control:
    loop_var: export_item
